name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libglfw3-dev
    - name: Build libmlx42.a
      run: |
        cd lib/MLX42
        cmake -B build
        cmake --build build -j4
    - name: Build cub3D
      run: |
        make


